spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/${db-name}?allowPublicKeyRetrieval=true&useSSL=false"
    username: "${db-username}"
    password: "${db-password}"
  jpa:
    show_sql: true
    hibernate:
      ddl_auto: "update"
    properties:
      format_sql: true
      dialect: "org.hibernate.dialect.MySQL8Dialect"
      jdbc:
        batch_size: 10
